name: Deploy

on:
  workflow_call:
    secrets:
      GOOGLE_CLOUD_KEY:
        required: true
      MEDCASE_GITHUB_TOKEN:
        required: true
      STAGE:
        required: true
env:
  MEDCASE_GITHUB_TOKEN: ${{ secrets.MEDCASE_GITHUB_TOKEN }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: yarn install
      - run: yarn build:${{ secrets.STAGE }}
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.MEDCASE_GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.GOOGLE_CLOUD_KEY }}"
          channelId: live
