name: Deploy

on:
  workflow_call:
    secrets:
      GOOGLE_CLOUD_KEY:
        required: true
      MEDCASE_GITHUB_TOKEN:
        required: true
      PROJECT_ID:
        required: true
env:
  MEDCASE_GITHUB_TOKEN: ${{ secrets.MEDCASE_GITHUB_TOKEN }}
  PROJECT_ID: ${{ secrets.PROJECT_ID }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
      - uses: actions/checkout@v2
      - run: cp .npmrc .npmrc.temp
      - uses: danielr1996/envsubst-action@1.0.0
        with:
          input: .npmrc.temp
          output: .npmrc
      - id: 'auth'
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: ${{ secrets.GOOGLE_CLOUD_KEY }}
      - id: deploy
        uses: google-github-actions/deploy-appengine@v0
      - id: url
        run: echo "${{ steps.deploy.outputs.url }}"
